services:
  web:
    build:
      context: ../../
      dockerfile: ./docker/dev/Dockerfile
    container_name: web
    restart: always
    command: sh -c "chmod +x ./scripts/wait-for-it.sh ; ./scripts/wait-for-it.sh postgres:5432 -- alembic upgrade head && uvicorn app.main:app --host 0.0.0.0"
    volumes:
      - ../../app:/home/app
    ports:
      - 8000:8000
    env_file:
      - ./.env
    environment:
      - DEBUG=True
    depends_on:
      - db

  db:
    image: postgres:15
    container_name: db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    env_file:
      - ./.env


volumes:
  postgres_data: